/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InputRouteImport } from './routes/input'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditingRouteImport } from './routes/auditing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUiuxRouteImport } from './routes/dashboard.uiux'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard.roadmap'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardCodeRouteImport } from './routes/dashboard.code'

const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditingRoute = AuditingRouteImport.update({
  id: '/auditing',
  path: '/auditing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUiuxRoute = DashboardUiuxRouteImport.update({
  id: '/uiux',
  path: '/uiux',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCodeRoute = DashboardCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditing': typeof AuditingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/error': typeof ErrorRoute
  '/input': typeof InputRoute
  '/dashboard/code': typeof DashboardCodeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uiux': typeof DashboardUiuxRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditing': typeof AuditingRoute
  '/error': typeof ErrorRoute
  '/input': typeof InputRoute
  '/dashboard/code': typeof DashboardCodeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uiux': typeof DashboardUiuxRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditing': typeof AuditingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/error': typeof ErrorRoute
  '/input': typeof InputRoute
  '/dashboard/code': typeof DashboardCodeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/uiux': typeof DashboardUiuxRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditing'
    | '/dashboard'
    | '/error'
    | '/input'
    | '/dashboard/code'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard/security'
    | '/dashboard/uiux'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditing'
    | '/error'
    | '/input'
    | '/dashboard/code'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard/security'
    | '/dashboard/uiux'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auditing'
    | '/dashboard'
    | '/error'
    | '/input'
    | '/dashboard/code'
    | '/dashboard/jobs'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard/security'
    | '/dashboard/uiux'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditingRoute: typeof AuditingRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  InputRoute: typeof InputRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditing': {
      id: '/auditing'
      path: '/auditing'
      fullPath: '/auditing'
      preLoaderRoute: typeof AuditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/uiux': {
      id: '/dashboard/uiux'
      path: '/uiux'
      fullPath: '/dashboard/uiux'
      preLoaderRoute: typeof DashboardUiuxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/code': {
      id: '/dashboard/code'
      path: '/code'
      fullPath: '/dashboard/code'
      preLoaderRoute: typeof DashboardCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCodeRoute: typeof DashboardCodeRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardUiuxRoute: typeof DashboardUiuxRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCodeRoute: DashboardCodeRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardUiuxRoute: DashboardUiuxRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditingRoute: AuditingRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ErrorRoute: ErrorRoute,
  InputRoute: InputRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
